apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-feedback
spec:
  replicas: {{ .Values.feedback.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-feedback
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-feedback
    spec:
      containers:
      - name: {{ .Release.Name }}-feedback
        image: "{{ .Values.feedback.image.repository }}:{{ .Values.feedback.image.tag }}"
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: {{ .Values.feedback.port }}
        env:
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis-service
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}