apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-feedback-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080" 
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-feedback
  ports:
  - protocol: TCP
    port: {{ .Values.feedback.port }}
    targetPort: {{ .Values.feedback.port }}