apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-feedback-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-feedback
  ports:
  - protocol: TCP
    port: {{ .Values.feedback.port }}
    targetPort: {{ .Values.feedback.port }}