version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  feedback-service:
    build: ./feedback-service
    image: feedback-service:latest
    container_name: feedback-service
    depends_on:
      - redis
    environment:
      SERVER_PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8081:8080"

  api-service:
    build: ./api
    image: riddle-api:latest
    container_name: api-service
    depends_on:
      - feedback-service
    environment:
      FEEDBACK_SERVICE_URL: http://localhost:8081
    ports:
      - "8000:8000"
