name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'services/**'

permissions:
  contents: write    # ‚Üê allows git push back to repo

jobs:
    build-and-push:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ vars.AWS_REGION }}

          - name: Login to ECR
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build and push API image
            uses: docker/build-push-action@v4
            with:
              context: ./services/api
              push: true
              tags: |
                ${{ secrets.ECR_REGISTRY }}/riddlebuddy:${{ github.sha }}

          - name: Build and push Feedback image
            uses: docker/build-push-action@v4
            with:
              context: ./services/feedback-service
              push: true
              tags: |
                ${{ secrets.ECR_REGISTRY }}/riddlebuddy-feedback:${{ github.sha }}

          - name: Update image tags in values.yaml
            run: |
              # install yq
              wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
              chmod +x /usr/local/bin/yq
              
              # update both tags
              yq e ".api.image.tag = \"${{ github.sha }}\"" -i helm/riddlebuddy/values.yaml
              yq e ".feedback.image.tag = \"${{ github.sha }}\"" -i helm/riddlebuddy/values.yaml

          - name: Commit and push
            run: |
              git config user.name "GitHub Actions"
              git config user.email "ci@github.com"
              git add helm/riddlebuddy/values.yaml
              git commit -m "ci: update image tag to ${{ github.sha }}"
              git push
