name: ðŸš€ Deploy AWS environment for Riddlebuddy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-southeast-1

      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run deploy
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          HOSTED_ZONE_ID:   ${{ secrets.HOSTED_ZONE_ID }}
          ACM_CERT_ARN:     ${{ secrets.ACM_CERT_ARN }}
        run: bash deploy-aws-env.sh
